# Generated by Django 5.0.2 on 2024-07-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_note_content_note_isediting_note_pinstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
