# Generated by Django 5.0.2 on 2024-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_note_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.CharField(blank=True, default='', max_length=10000),
        ),
    ]
