# Generated by Django 5.0.2 on 2024-07-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_note_created_at_note_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='name',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
